pypa/pyproject-metadata

pyproject_metadata/__init__.py
=> metadata: avoid first and last newlines in license contents

setup.cfg
See https://github.com/readthedocs/readthedocs.org/issues/9038
=> setup.cfg: constrain the jinja2 dependency

.github/workflows/tests.yml, pyproject_metadata/__init__.py, tests/packages/full-metadata/README.md, tests/packages/full-metadata2/LICENSE, tests/packages/full-metadata2/README.rst, tests/test_standard_metadata.py
Windows currently opens files with a potentially different encoding, meaning that if you put a unicode character in your readme it would fail to read the file.
closes #36
=> metadata: use utf-8 encoding when opening files

pyproject_metadata/__init__.py, setup.cfg
I recently saw this when trying to test scikit-build-core on conda, in preparation for conda-forge support:
```
File "C:\Miniconda\envs\test\conda-bld\scikit_build_example_1669132774510\_build_env\lib\site-packages\pyproject_metadata\__init__.py", line 13, in <module>
from typing import Any, DefaultDict, Dict, List, Mapping, Optional, OrderedDict, Tuple, Union
ImportError: cannot import name 'OrderedDict' from 'typing' (C:\Miniconda\envs\test\conda-bld\scikit_build_example_1669132774510\_build_env\lib\typing.py)
error: subprocess-exited-with-error
```
Checking, [it seems OrderedDict was added in 3.7.2](https://docs.python.org/3/library/typing.html#typing.OrderedDict). Better yet, just use non-deprecated `collections.OrderedDict` and utilize `from __future__ import annotations` to write …
=> typing: fix issues with Python <3.7.2 and simplify

.github/workflows/tests.yml
The required tests are broken due to changing the job names (win + ubuntu instead of one run each). This adds a single job that can be used to gate on, and then it will work in the future even if jobs changed (and old jobs won't all turn orange when things change, too). This needs to be updated in the branch protection (@FFY00). I've taken the naming from pypa/build.
=> ci: add all checks pass check

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
Making a msg modifies the metadata each time.
As a temporary workaround, `copy.deepcopy(metadata).as_rfc822()` can be used by user code.
=> fix: metadata modified by printing msg

tests/test_standard_metadata.py
Tests were broken by a recent push to main. I'd recommend not pushing to main, and if really required, running pytest/nox first. :)
=> tests: tests were broken

.pre-commit-config.yaml, pyproject.toml, pyproject_metadata/__init__.py, setup.cfg, tests/conftest.py, tests/test_standard_metadata.py
Move to using Ruff. Adding some standard pytest config too, since I misspelled a marker and it let it through.
=> ruff: replace flake8 and isort with ruff

pyproject_metadata/__init__.py
ConfigurationError is raised with key `project.license` which should be `project.readme`
=> correct exception key in StandardMetadata_get_readme

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
The core metadata specification link: https://packaging.python.org/en/latest/specifications/core-metadata/#id14
=> fix: use comma to separate keywords

.pre-commit-config.yaml, pyproject_metadata/__init__.py
See https://github.com/scientific-python/cookie/pull/200.
=> chore: ruff moved to astral-sh

.readthedocs.yml, pyproject.toml
RtD requires the build: os: table now, as promised for a few months. Can be seen via:
https://learn.scientific-python.org/development/guides/repo-review/?repo=FFY00/python-pyproject-metadata&branch=main
=> ci: fix readthedocs

pyproject.toml
Using the modern lint section for linting options. target-version is no longer necessary if using PEP 621. Minor other tweaks.
=> chore: modernize Ruff config

pyproject_metadata/__init__.py, tests/packages/full-metadata/pyproject.toml, tests/test_standard_metadata.py
This is a proposed fix for https://github.com/FFY00/python-pyproject-metadata/issues/60. I've preserved the original name and provided a property to get the canonical name too (is this a good idea? Or just document `packaging.utils.canonicalize_name`?).
What do you think?
=> fix: preserve user specified name in metadata

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
Fix #67.
Will followup later, but this should fix the problem above.
I think the long term fix that would allow the rest of the fields might be as follows: add a new field `_value_added`. Whenever a user sets a value, `value_added` records it. Then we can compute `set(dynamic) - set(value_added)` and if anything is left, that's Metadata 2.2 dynamic. This feels safer than modifing the dynamic field.
=> fix: require version in dynamic if unset

.github/workflows/tests.yml, pyproject.toml, pyproject_metadata/__init__.py
This makes the tracebacks cleaner by not repeating the error message. And it also clarifies that `key=` isn't affecting the `{key}` field in many of the strings.
Also was doing some cleanup related to line length (using fully qualified types in type expressions makes them too long, so fixing one of them).
=> fix: cleaner tracebacks

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
Working on supporting metadata 2.3 and allowing a backend to choose what version they want.
In draft until I add tests.
=> feat: support metadata 2.1-2.3

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
Other implementations of core metadata generation support specifying empty extras. These are useful for backwards compatibility purposes. For example,
<https://github.com/tiangolo/typer/discussions/785#discussioncomment-9032083>.
The Core metadata specifications document says:
> It is legal to specify `Provides-Extra:` without referencing it in any
> `Requires-Dist:`.
Ref: https://packaging.python.org/en/latest/specifications/core-metadata/#provides-extra-multiple-use
=> Allow specifying empty extras

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
This was just filling out 100% coverage noticed by #94, but found a small error message fix, missing f-string.
=> fix: configuration error printout missing values

CHANGELOG.rst, README.md, pyproject_metadata/__init__.py
Preparing for a release (mentioned in https://github.com/FFY00/python-pyproject-metadata/pull/83).
=> docs: update changelog for 0.8.0rc1

.github/workflows/tests.yml
ARM is fine, no Python 3.8 or 3.9 is not.
=> ci: macos-latest now points at macos-14

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
=> metadata: validate entrypoint group names

noxfile.py, pyproject_metadata/__init__.py
This fixes the typing for emails. Fix #126.
=> fix(types): Correct typing for emails

pyproject.toml, tests/test_standard_metadata.py
This was producing an annoying in the test output, since we were requesting the html context, but not enabling it.
=> tests: fix coverage context

pyproject_metadata/__init__.py, tests/test_internals.py
This is some refactoring for the fetcher methods that didn't live inside the fetcher.
Originally I was moving them to free functions, which is why the `__all__` addition is here.
Coverage is 100% now.
=> refactor: move fetcher methods

noxfile.py, tests/test_internals.py, tests/test_standard_metadata.py
This was not readable in verbose mode. This is what it looks like now:
```
tests/test_standard_metadata.py::test_load[Missing project section] PASSED                                                                                              [ 15%]
tests/test_standard_metadata.py::test_load[Missing project name] PASSED                                                                                                 [ 17%]
tests/test_standard_metadata.py::test_load[Invalid name type] PASSED                                                                                                    [ 18%]
tests/test_standard_metadata.py::test_load[Unsupported field in project.dynamic] PASSED                                                                                 [ 19%] …
```
=> tests: add human readable IDs

pyproject_metadata/__init__.py, tests/test_rfc822.py
This brings us more in line with the spacing from `email.message.EmailMessage`.
=> fix: match EmailMessage spacing

README.md, pyproject_metadata/__init__.py, tests/test_standard_metadata.py
Fix #12. ~~This is currently opt-in, though I think it could be made opt-out in the future.~~ Edit: made it default to warning, opt-in for strict or ignore.
There are also two extra helper functions to validate the rest of the pyproject.toml for extra keys. But this is stricter than the project table, which is all that pyproject-metadata handles, so those are not potentially opt-out or even "integrated", but just helpers to provide a consistent error system if backends want to use it (I think most would, I will be calling them too in scikit-build-core).
These could be turned into warnings by backends if they prefer by catching the error and emitting a warning. `allow_extra_keys=None` could produce a warning,actually, that's not a bad idea and a pretty reasonable default. Edit: done.
=> feat: validate extra keys (warning, opt-in error)

README.md, pyproject_metadata/__init__.py, tests/test_rfc822.py, tests/test_standard_metadata.py
This is the beginning part of #142, without the move to `email.message.EmailMessage`.
=> refactor: prepare for EmailMessage

pyproject_metadata/__init__.py, tests/test_rfc822.py
Make `RFC822` a subclass of `EmailMessage` and remove all reliance on custom behaviors.
Close #101.
=> refactor: use EmailMessage class

README.md, pyproject.toml, pyproject_metadata/__init__.py, tests/packages/spdx/pyproject.toml, tests/test_standard_metadata.py
This adds PEP 639 support. Details for backends mentioned in readme.
I left normalization and validation to packaging (https://github.com/pypa/packaging/pull/828), otherwise we'd want to basically vendor that code _and_ keep a license list up to date.
Close https://github.com/pypa/pyproject-metadata/issues/130.
=> feat: adding PEP 639 support

pyproject_metadata/__init__.py, tests/test_rfc822.py
This adds a warning in followup to https://github.com/pypa/pyproject-metadata/pull/142#discussion_r1757557104.
=> fix: add multiline warning

.github/workflows/tests.yml, CHANGELOG.rst
Getting ready for a beta release, to make it easier for backend authors to test out PEP 639 and the new validation errors and warnings.
=> docs: prepare changelog for 0.9.0b1

pyproject.toml, pyproject_metadata/__init__.py, tests/test_rfc822.py
Fix for #149. Changes:
* Support unicode METADATA
* Remove the custom `RFC822Message` entirely, replaced with a custom Policy (which also handles multilines
* Handle multiline the way setuptools does with smart indentation
* Remove `write_to_rfc822`
* Remove the multiline warning for all metadata
* Add some unicode and reading tests
* Swap `EmailMessage` for `Message`
=> fix: add unicode and join multilines

README.md, pyproject_metadata/__init__.py, tests/test_rfc822.py
Try for #149 again. RFC822Message is back, but based on EmailMessage. A slightly better name for it might be `UnicodeMessage`. Restoring `write_to_rfc822`.
=> fix: handle bytes() if payload has unicode

CHANGELOG.rst
Most users don't care about beta changes. They are still in the GitHub releases if someone does care.
=> docs: merge changelog, use GitHub changelog for pre-release differences

pyproject_metadata/__init__.py
Dataclasses don't leak unused APIs like iteration, unpacking, Sequence, etc.
=> refactor: dataclass instead of named tuple

pyproject_metadata/__init__.py
Can't use kw_only yet (3.10+), but let's at least move this call to keywords, as it's quite long and easy to mess up.
=> chore: use named arguments instead of positional

README.md, pyproject_metadata/__init__.py, tests/test_rfc822.py, tests/test_standard_metadata.py
This reworks how "dynamic" works. The old way was quite broken: Because a field is project dynamic, that doesn't mean it's METADATA dynamic. And the METADATA dynamic field names are METADATA names, not project names.
This has to be split into two concepts. There's a new `metadata_dynamic` value that backends can set if they are setting dynamic metadata. If we provide a mapping, we can specify this as project field names, currently it's just METADATA field names. Will have to see which makes the most sense. This _must_ be set by the backend if it wants to make a METADATA 2.2 dynamic field. It's not information present in the pyproject.toml. Though it is a strict subset (with appropriate name conversions).
~~The regular "dynamic" field now is used to keep users from setting any unlisted …
=> refactor: rework how dynamic works

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
Pulled out from #157. We can make this a warning instead if it trips up anyone in beta.
=> feat: setting a non-dynamic field is an error

README.md
Close #46 by providing an example. I expect build backends should mostly not do this, since you should be able to build with a new classifier that PyPI supports, but wasn't known when the build backend was packaged. It's better to validate with tools that check wheels. Though some build-backends might want optional validation. Other tools likely will want validation.
=> docs: example for classifier validation

pyproject.toml, pyproject_metadata/__init__.py, tests/test_standard_metadata.py
Add a warning instead of https://github.com/pypa/pyproject-metadata/pull/76. See #30.
=> fix: warn on multiline Summary (project.description)

CHANGELOG.rst, pyproject_metadata/__init__.py
After #162, so backends can test the dynamic metadata changes.
=> docs: prepare for 0.9.0b4

pyproject.toml, pyproject_metadata/project_table.py
This is an initial attempt to add a TypedDict for the pyproject.toml input. Unfortunately, DataFetcher kills all internal static type info so this isn't checked. Working on this primarily for https://github.com/pypa/packaging/issues/647.
=> feat(types): Add TypedDict

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
This replaces the DataFetcher with simple functions and direct dict access to preserve static types. This allows #128 to self validate most of the operations internally. This was how I found the `entrypoints` -> `entry-points` bug in #128 that I fixed before merging.
Will refactor into a file since this would be nicer for organisation, since all these functions are grouped into "accessing the pyproject dict" (and aren't public, which is reflected in `__all__`, but better to fully hide, IMO).
=> refactor: remove data fetcher, use static types where possible

pyproject_metadata/__init__.py, pyproject_metadata/constants.py, pyproject_metadata/errors.py, pyproject_metadata/pyproject.py, tests/test_internals.py, tests/test_rfc822.py
Builds on #165.
This breaks out helpers into separate files. This helps protect our API against accidental usage, and groups related functions together. The new files are:
* `constants.py`: Sets of field names and mappings and known metadata versions
* `pyproject.py`: Functions related to reading the pyproject.toml
* `errors.py`: Our error definitions
=> refactor: files

pyproject.toml, pyproject_metadata/__init__.py, pyproject_metadata/pyproject.py
These are just annoying to skip, and aren't really helping that much. There's also a nearly identical C check anyway.
=> chore: remove PLR09 checks

README.md, pyproject.toml, pyproject_metadata/__init__.py, pyproject_metadata/errors.py, pyproject_metadata/pyproject.py, tests/test_standard_metadata.py
Close #45. Adds an `all_errors` parameter that causes all errors to be collected and shown in a ExceptionGroup. The output is a bit ugly for \<3.11, but no dependency is required. A build backend can use the backport by replacing `pyproject_metadata.errors.ExceptionGroup`.
If we submit to packaging, this would be the default there #140. And if we do, then I'd be very likely to want the back port here eventually, since a user can use packaging if they need minimal deps. Though, "eventually" probably would be around the time 3.11 becomes the minimum... so yeah, might not happen.
I've also added quite a few missing `key=` params as well as provided better descriptions in a few cases.
=> feat: all_errors

CHANGELOG.rst, pyproject_metadata/__init__.py
Last thing is #175 and it's followup, which will go in the next beta (might be RC?), not this one. Then after maintainer testing and signoff, we'll be ready for release.
=> docs: prepare for 0.9.0b5

README.md
Add PyPI badge, fix a few links. Fixes the "docs unknown" badge. Cleaner.
=> docs: badges in readme update

README.md, pyproject_metadata/__init__.py, pyproject_metadata/errors.py, tests/test_standard_metadata.py
This feels like a simpler solution to #178. It just simplifies the "validate_*" functions to producing a set of extra fields, so the consumer can choose what to do with them. This also simplifies the implementation of allow_extra_keys, too.
=> refactor: validate -> extras functions

docs/conf.py, noxfile.py, pyproject.toml, pyproject_metadata/__init__.py, pyproject_metadata/constants.py, pyproject_metadata/errors.py, pyproject_metadata/project_table.py, pyproject_metadata/pyproject.py, tests/test_internals.py, tests/test_rfc822.py, tests/test_standard_metadata.py
This uses more standard formatting style, which should better match pypa/packaging (preparing for #103). No content changes were made except removing custom format configuration.
I will make a followup to replace `f'This is a value: "{value}"'` strings with `f"This is a value: {value!r}"`, which will use a more Python-like `'` in the error message, and will handle incorrect types better - currently `2` is printed as `"2"`, which makes it look like a string.
=> chore: reformat to match packaging

docs/changelog.md, docs/changelog.rst
Makes adding the GitHub Release easier.
=> docs: changelog as markdown

pyproject_metadata/__init__.py, pyproject_metadata/pyproject.py, tests/test_rfc822.py, tests/test_standard_metadata.py
Promised follow to #175. Now the error messages produce standard output like Python, such as `Field 'project.thing' got 'value'`. By matching the built-in repr style, we can now use repr directly, which fixes the display when printout out a non-string, instead of things like `"True"`, `"13"`, `"{}"`, etc. The confusing `wrong type, expected string (got "2")` messages are finally better. :)
As usual, while going over this, fixed minor things. In this case, an extra `,` in a error message.
=> fix: produce standard Python repr style

docs/changelog.md, pyproject_metadata/__init__.py, tests/test_standard_metadata.py
I think this is the last beta.
=> docs: prepare for 0.9.0b6

docs/api/pyproject_metadata.rst, docs/conf.py, noxfile.py, pyproject.toml, pyproject_metadata/__init__.py, pyproject_metadata/errors.py, pyproject_metadata/pyproject.py
Reordering, removing duplicates, etc.
=> docs: add more docs, polish presentation

pyproject_metadata/__init__.py, pyproject_metadata/errors.py, pyproject_metadata/pyproject.py, tests/test_standard_metadata.py
Fixes type name errors to show the type. Nested types handled. Also fixes an issue with extra keys in author/maintainer.
See comments on #183 and Discord.
=> fix: show type name in errors about types

docs/changelog.md, pyproject_metadata/__init__.py
Small recent changes to error messages.
=> docs: prepare for 0.9.0b7

CHANGELOG.rst, pyproject_metadata/__init__.py
Preparing for 0.8.1 while we wait for 0.9.0 to be evaluated by build backends. Getting that 3.13 classifier on Python 3.13.0 release day.
=> [v0.8] chore: release 0.8.1

pyproject_metadata/project_table.py
=> feat: add types for PEP 735

pyproject.toml, pyproject_metadata/__init__.py, pyproject_metadata/constants.py, tests/test_standard_metadata.py
Just accepted!
This follows [PEP 753](https://peps.python.org/pep-0753):
* Home-page is not emitted anymore
* URL names are not normalized
And:
* The key for a URL can't be more than 32 chars
=> feat: follow PEP 753

README.md, pyproject_metadata/__init__.py, tests/packages/fulltext_license/LICENSE.txt, tests/test_standard_metadata.py
I think this correctly handles the case when METADATA 2.4+ is set and old license settings are used.
I don't think the PEP is clear on what to do with License (see discussion in #202), so I'm leaving it alone, based on a comment on https://discuss.python.org/t/pep-639-round-3-improving-license-clarity-with-better-package-metadata/53020/124.
=> fix: support METADATA 2.4 being set explicilty & PEP 639

.github/workflows/tests.yml, README.md, pyproject_metadata/__init__.py, tests/test_standard_metadata.py
If we do want to remove attribute locking for non-dynamic fields, this is what it would look like. It can get in the way in a few valid cases (see #202). Maybe it's better to just leave it up to the backends to check the dynamic array? They probably never want our error to surface, anyway, as it's always a backend error to hit this.
Another option is we could make it smarter, allowing normalization for some fields. I just think the new license field might be tricky to validate if it's just a normalization? Or maybe not?
Or we can leave it.
=> revert: remove attribute locking

docs/changelog.md, pyproject_metadata/__init__.py
I don't forsee any more changes before 0.9.0. I'll make sure this works in scikit-build-core, then will be ready for release!
=> docs: prepare for 0.9.0rc1

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
Some minor touchup based on packaging PR.
=> fix: some touchup based on packaging PR

.github/workflows/tests.yml, .pre-commit-config.yaml, noxfile.py, pyproject_metadata/__init__.py, tests/packages/broken_license/LICENSE, tests/test_standard_metadata.py
Alternative to, and close #230. See https://github.com/scikit-build/scikit-build-core/issues/1006.
Checked with `uv run --python 3.12.3 pytest` and `uv run --python 3.12.4 pytest`. (and 3.13.0 for good measure)
=> fix: handle form feed for Python <3.12.4

pyproject.toml
`InvalidName` was added in this version.
=> fix: min version of packaging was wrong in 0.9.1

.github/workflows/tests.yml, .readthedocs.yml, noxfile.py, pyproject.toml
Using dependency-groups.
Checking the minimum limits. Some test dependencies have been bumped a little.
=> chore: use dependency-groups, check minimums

pyproject.toml
https://astral.sh/blog/ruff-v0.9.0#fewer-single-line-implicitly-concatenated-strings
=> ISC rules do not conflict with the formatter any more
