README.md
Thank you very much for the handy library @FFY00.
I tried to put up together a PR to add some clarifications and usage to the README.
Hopefully it is useful for you.
=> readme: add some details and usage

pep621.py, tests/test_standard_metadata.py
=> pep621: error out when dynamic fields are defined

pep621.py, tests/test_standard_metadata.py
=> pep621: support multiple clauses in requires-python

pep621.py, tests/test_standard_metadata.py
=> pep621: update dynamic field when setting version

pyproject_metadata/__init__.py, tests/test_rfc822.py
=> metadata: add support for multiline data in metadata fields

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
=> metadta: write license text to the metadata file

README.md
=> readme: fix typo in example

pyproject_metadata/__init__.py
=> metadata: update RFC822Message's docstring

setup.cfg, tests/test_standard_metadata.py
=> tests: compat with packaging/22.0

.pre-commit-config.yaml
=> ci: fix broken Poetry + isort issue

pyproject.toml, setup.cfg
Quick cleanup. I'd like to try moving the backend to flit-core, but thought I'd do these things first.
=> setup.cfg: minor touchup to metadata

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
=> fix: validate description

.github/workflows/tests.yml, .gitignore, noxfile.py, pyproject.toml
=> chore: update for 3.12 in CI

pyproject_metadata/__init__.py, tests/test_rfc822.py
Signed-off-by: Frost Ming <me@frostming.com>
Fix #82
=> fix: concatenate the markers with extra marker

.github/workflows/release.yml
Signed-off-by: Frost Ming <me@frostming.com>
This uses the excellent action developed by @hynek and [PyPI trusted publisher](https://docs.pypi.org/trusted-publishers/), which requires maintainers' action to set it up.
This also addresses https://github.com/FFY00/python-pyproject-metadata/pull/83#issuecomment-1911474463
@FFY00 @pradyunsg
=> feat(ci): automated release workflow

pyproject_metadata/__init__.py
=> fix: typing annotation for StandardMetadata.from_pyproject()

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
=> fix: typo in exception message

CHANGELOG.rst, pyproject_metadata/__init__.py
=> chore: bump to 0.8.0rc2

CHANGELOG.rst, pyproject_metadata/__init__.py
=> chore: bump to 0.8.0

.pre-commit-config.yaml, noxfile.py, pyproject.toml, pyproject_metadata/__init__.py, tests/test_rfc822.py, tests/test_standard_metadata.py
=> chore: add ruff-format

pyproject_metadata/__init__.py, tests/test_standard_metadata.py
=> feat: validate project name

.github/workflows/tests.yml, noxfile.py, pyproject.toml
=> chore: add 3.13 to testing

pyproject_metadata/__init__.py
=> refactor: put validation in function

.github/release.yml
Makes it easier to see what's changed.
=> ci: better changelog auto-generation

pyproject_metadata/__init__.py
=> chore: prepare for 0.9.0b1

CHANGELOG.rst, pyproject_metadata/__init__.py
=> chore: prepare for 0.9.0b2

CHANGELOG.rst, pyproject_metadata/__init__.py
=> docs: prepare changelog for 0.9.0b3

tests/test_rfc822.py
Adding some more readable IDs to tests.
=> tests: more readable ids

pyproject_metadata/__init__.py
This is a bit simpler and more natural, and makes the default constructor simpler. The only downside is that you now need `auto_metadata_version` to compute the metadata-version from None; `.metadata_version` will return None if it's None.
=> refactor: remove indirection accessing metadata_version, add auto_metadata_version

pyproject_metadata/__init__.py, pyproject_metadata/constants.py, tests/test_standard_metadata.py
AFAICT, there's not an official file name for this yet, but METADATA 2.1 prescribes the format.
=> feat: support METADATA 2.1+ json format

tests/test_rfc822.py
Making sure we handle https://github.com/pypa/setuptools/issues/3808 correctly.
=> tests: check long version

pyproject_metadata/__init__.py, pyproject_metadata/errors.py, pyproject_metadata/pyproject.py
Making this easier to change `'key'` back to `"key"` (see https://github.com/pypa/pyproject-metadata/pull/183#issuecomment-2384736605)
=> refactor: make config_error smarter

.github/workflows/tests.yml, .pre-commit-config.yaml, README.md, docs/changelog.md, docs/index.md, pyproject.toml, pyproject_metadata/__init__.py, pyproject_metadata/errors.py, tests/test_rfc822.py, tests/test_standard_metadata.py
Adding more checks and formatters.
=> chore: add more checks and formatters

pyproject_metadata/constants.py, tests/test_standard_metadata.py
=> fix: support PEP 735 in top level validation

docs/changelog.md, pyproject_metadata/__init__.py
=> chore: bump to 0.9.0

.github/workflows/checks.yml, .github/workflows/tests.yml, .readthedocs.yml, noxfile.py, pyproject.toml, pyproject_metadata/project_table.py, tests/test_standard_metadata.py
Should fix our CI, and has been planned for quite a while.
=> feat: drop Python 3.7

docs/changelog.md, pyproject_metadata/__init__.py
Preparing for 0.9.1 (in v0.9 branch).
=> docs: prepare for 0.9.1

docs/changelog.md
=> docs: correct release date for 0.8.1

noxfile.py, pyproject.toml
We already added testing, so let's add the classifier now that 3.14b1 is out!
=> chore: add 3.14 classifier

pyproject.toml
=> chore: use PEP 639 license
